### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by craigmillernz** [groupeLIAMG/pycpd#1]
Hi

I'm having trouble compiling pycpd, with the cython extension.

Screen dump below.  I'm running python 2.7 on windows10.

Regards
Craig

#########################
python setup.py build_ext --inplace
running build_ext
skipping 'radon.c' Cython extension (up-to-date)
building 'radon' extension
C:\Users\xxxx\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\ProgramData\Anaconda2\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda2\include -IC:\ProgramData\Anaconda2\PC /Tcradon.c /Fobuild\temp.win-amd64-2.7\Release\radon.obj -std=c99
cl : Command line warning D9002 : ignoring unknown option '-std=c99'
radon.c
c:\programdata\anaconda2\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
radon.c(8520) : warning C4293: '<<' : shift count negative or too big, undefined behavior
radon.c(8530) : warning C4293: '<<' : shift count negative or too big, undefined behavior
radon.c(8540) : warning C4293: '<<' : shift count negative or too big, undefined behavior
radon.c(8704) : warning C4293: '<<' : shift count negative or too big, undefined behavior
radon.c(8714) : warning C4293: '<<' : shift count negative or too big, undefined behavior
radon.c(8724) : warning C4293: '<<' : shift count negative or too big, undefined behavior
radon.c(8772) : warning C4293: '<<' : shift count negative or too big, undefined behavior
radon.c(8782) : warning C4293: '<<' : shift count negative or too big, undefined behavior
radon.c(8792) : warning C4293: '<<' : shift count negative or too big, undefined behavior
radon.c(9415) : warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data
radon.c(9421) : warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data
C:\Users\xxxx\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\ProgramData\Anaconda2\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda2\include -IC:\ProgramData\Anaconda2\PC /Tccradon.c /Fobuild\temp.win-amd64-2.7\Release\cradon.obj -std=c99
cl : Command line warning D9002 : ignoring unknown option '-std=c99'
cradon.c
cradon.c(1) : error C2773: #import and #using available only in C++ compiler
cradon.c(8) : error C2143: syntax error : missing ')' before '*'
cradon.c(8) : error C2081: 'PyObject' : name in formal parameter list illegal
cradon.c(8) : error C2143: syntax error : missing '{' before '*'
cradon.c(8) : error C2059: syntax error : ')'
cradon.c(8) : error C2054: expected '(' to follow 'L'
error: command 'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

**Comment by bernard-giroux** [comment]
Hi Craig,

Unfortunately, I don't have much experience compiling on windows.  It looks like the compiler is not recognizing cradon.c as C.  Do you know what option should be given in place of -std=c99 (which is used on linux/mac)?

Also, it looks like the file radon.c is already there.  Was it generated previously on your system?  If not, try erasing it (it is generated by python).

**Comment by craigmillernz** [comment]
Hi Bernard

Thanks for the reply.  I found this.
https://software.intel.com/en-us/articles/c99-support-in-intel-c-compiler

but using the /Qstd=c99 didn't work either. The radon.c was made from previous attempts, I deleted it but have the same issue.

I'll let you know if I find the solution!
C

**Comment by bernard-giroux** [comment]
I guess I'm doing too much python vs C these days...  I had to #include, not #import ...  now fixed.
