### ISSUE TITLE
Transverse Mercator projection

### ISSUE THREAD

**Issue by craigmillernz** [groupeLIAMG/pycpd#2]
Hi,  I notice you don't have a transverse mercator projection, only lambert conformal.  Would it be possible to at the transverse mercator?  I can also have go at it and create a pull request if you like?
Thanks for making is code, it could be quite useful!

**Comment by bernard-giroux** [comment]
It certainly is possible.  I'll have a look next week, but feel free to give it a go if you like.

**Comment by bernard-giroux** [comment]
Would you like to have write permission, or forking is OK with you?

**Comment by bernard-giroux** [comment]
Actually, the projection can be defined when the mag data are loaded, in a custom QDialog window (with the appropriate proj4 string).  If you give me the string(s) for your data, I can add those to the list of predefined protection parameters.

**Comment by bernard-giroux** [comment]
OK, I see that downstream, transverse mercator is not handled (I do not work often on this code...).  I'll have a look.

**Comment by bernard-giroux** [comment]
Please have a try now

**Comment by craigmillernz** [comment]
thanks, looks like it works.

**Comment by bernard-giroux** [comment]
Great.  Don't hesitate to get in touch if you find bugs.
