### ISSUE TITLE
Read other grid formats

### ISSUE THREAD

**Issue by craigmillernz** [groupeLIAMG/pycpd#3]
Would it be possible to include readers for other more standard grid format?  Neither netcdf or usgs are particularly common formats for this kind of data.  Perhaps gdal could be used to parse a wider range of grids?

**Comment by bernard-giroux** [comment]
Using gdal is a good idea.  I'll try to find some time to do it next week.

**Comment by bernard-giroux** [comment]
Done.  Give it a go when you have time.

**Comment by craigmillernz** [comment]
Hi Many thanks for implementing the gdal option. My "gdal" grids don't have the projection built in so I specified the custom proj4 string and then selected the GDAL driver from the file selector box.  The grid loads, but is mirror imaged or flipped somehow??

**Comment by bernard-giroux** [comment]
Is it flipped north-south ?

**Comment by craigmillernz** [comment]
That last update fixed the flip issue. :-)

**Comment by bernard-giroux** [comment]
Great
