### ISSUE TITLE
The user interface released?  

### ISSUE THREAD

**Issue by MsBruce** [groupeLIAMG/pycpd#4]
Dear,
when the user interface will be released?

**Comment by bernard-giroux** [comment]
Hi,it is part of the code already.  You should be able to access the user interface by typing `python pycpd.py`

**Comment by MsBruce** [comment]
Dear,
Thanks very much, and my computer cannot install pyqt5. So, If it's convenient, or when you have time, could you please send me a *.exe to me?    Thank you very much. and my email is 1477868714@qq.com.

**Comment by bernard-giroux** [comment]
Sorry, I do not work on a windows machine and I cannot build an executable.  Try installing [anaconda python](https://www.anaconda.com), I think it comes with pyqt5.
